-- Database: quetal

-- DROP DATABASE quetal;

-- CREATE DATABASE quetal
--   WITH OWNER = quetal
--        ENCODING = 'UTF8'
--        TABLESPACE = pg_default
--        LC_COLLATE = 'Portuguese_Brazil.1252'
--        LC_CTYPE = 'Portuguese_Brazil.1252'
--        CONNECTION LIMIT = -1;

-- CREATE TABLE usuario(
-- id serial primary key,
-- nome varchar(50),
-- sobrenome varchar(50),
-- dataNasc date,
-- email varchar(100),
-- senha varchar(100)
-- );
-- 
-- CREATE TABLE empresa(
-- id serial primary key,
-- nome varchar(100),
-- tipo int
-- );
-- 
-- CREATE TABLE interesse(
-- id serial primary key,
-- tipo varchar(50)
-- );
-- 
-- 
-- INSERT INTO interesse (tipo) VALUES ('Pipoca');
-- INSERT INTO interesse (tipo) VALUES ('Música');
-- INSERT INTO interesse (tipo) VALUES ('Comida');
-- INSERT INTO interesse (tipo) VALUES ('Passeio');
-- INSERT INTO interesse (tipo) VALUES ('Bebida');
-- INSERT INTO interesse (tipo) VALUES ('Companhia');
-- INSERT INTO interesse (tipo) VALUES ('Festa');
-- INSERT INTO interesse (tipo) VALUES ('Fim de Tarde');
-- INSERT INTO interesse (tipo) VALUES ('Noite');
-- 
-- 
-- 
-- CREATE TABLE us_int(
-- id serial primary key,
-- id_us int references usuario(id) ON DELETE CASCADE,
-- id_int int references interesse(id) ON DELETE CASCADE
-- );
-- 
-- CREATE TABLE emp_int(
-- id serial primary key,
-- id_emp int references empresa(id) ON DELETE CASCADE,
-- id_int int references interesse(id) ON DELETE CASCADE
-- );

-- DROP TABLE usuario, empresa, interesse, us_int, emp_int;
SELECT * FROM us_int;
-- SELECT * FROM empresa where carac like '' ;
-- DELETE FROM usuario where id=3;