-- Database: quetal

-- DROP DATABASE quetal;

-- CREATE DATABASE quetal
--   WITH OWNER = quetal
--        ENCODING = 'UTF8'
--        TABLESPACE = pg_default
--        LC_COLLATE = 'Portuguese_Brazil.1252'
--        LC_CTYPE = 'Portuguese_Brazil.1252'
--        CONNECTION LIMIT = -1;

-- CREATE TABLE usuario(
-- id serial PRIMARY KEY,
-- nome varchar(50),
-- sobrenome varchar(50),
-- dataNasc date,
-- email varchar(100),
-- senha varchar(100)
-- );
-- 
-- CREATE TABLE empresa(
-- id serial PRIMARY KEY,
-- nome varchar(100),
-- tipo varchar(50),
-- );

-- 
-- INSERT INTO empresa (nome, tipo) VALUES ('papito', 'restaurante');
-- INSERT INTO empresa (nome, tipo) VALUES ('sorelle', 'restaurante');
-- INSERT INTO empresa (nome, tipo) VALUES ('cine super k', 'cinema');
-- INSERT INTO empresa (nome, tipo) VALUES ('cachaçaria', 'restaurante');
-- INSERT INTO empresa (nome, tipo) VALUES ('cine araujo', 'cinema');
-- INSERT INTO empresa (nome, tipo) VALUES ('cinemerk', 'cinema');
-- INSERT INTO empresa (nome, tipo) VALUES ('santa cerva', 'balada');
-- INSERT INTO empresa (nome, tipo) VALUES ('opium motel', 'motel');
-- INSERT INTO empresa (nome, tipo) VALUES ('lebaron', 'motel');
-- INSERT INTO empresa (nome, tipo) VALUES ('buritis', 'motel');
-- INSERT INTO empresa (nome, tipo) VALUES ('c q sabe', 'motel');
-- INSERT INTO empresa (nome, tipo) VALUES ('x.com', 'restaurante');
-- INSERT INTO empresa (nome, tipo) VALUES ('cajueiro', 'restaurante');
-- INSERT INTO empresa (nome, tipo) VALUES ('ville roy grill', 'restaurante');
-- INSERT INTO empresa (nome, tipo) VALUES ('ch bar', 'balada');
-- INSERT INTO empresa (nome, tipo) VALUES ('antique', 'balada');
-- INSERT INTO empresa (nome, tipo) VALUES ('marina', 'balada');
-- INSERT INTO empresa (nome, tipo) VALUES ('almirante', 'balada');
-- INSERT INTO empresa (nome, tipo) VALUES ('haras cunhãpuca', 'balada');
-- INSERT INTO empresa (nome, tipo) VALUES ('praça das águas', 'passeio');
-- INSERT INTO empresa (nome, tipo) VALUES ('praça da bandeira', 'passeio');
-- INSERT INTO empresa (nome, tipo) VALUES ('complexo airton senna', 'passeio');
-- INSERT INTO empresa (nome, tipo) VALUES ('praça germano sampaio', 'passeio');
-- INSERT INTO empresa (nome, tipo) VALUES ('orla taumanã', 'passeio');
-- 

-- CREATE TABLE interesse(
-- id serial PRIMARY KEY,
-- tipo varchar(50)
-- );
-- 
-- 
-- INSERT INTO interesse (tipo) VALUES ('Pipoca');1
-- INSERT INTO interesse (tipo) VALUES ('Música');2
-- INSERT INTO interesse (tipo) VALUES ('Comida');3
-- INSERT INTO interesse (tipo) VALUES ('Passeio');4
-- INSERT INTO interesse (tipo) VALUES ('Bebida');5
-- INSERT INTO interesse (tipo) VALUES ('Companhia');6
-- INSERT INTO interesse (tipo) VALUES ('Festa');7
-- INSERT INTO interesse (tipo) VALUES ('Fim de Tarde');8
-- INSERT INTO interesse (tipo) VALUES ('Noite');9
-- 
-- 
-- 
-- CREATE TABLE us_int(
-- id serial PRIMARY KEY,
-- id_us int REFERENCES usuario(id) ON DELETE CASCADE,
-- id_int int REFERENCES interesse(id) ON DELETE CASCADE
-- );
-- 
-- CREATE TABLE emp_int(
-- id serial PRIMARY KEY,
-- id_emp int REFERENCES empresa(id) ON DELETE CASCADE,
-- id_int int REFERENCES interesse(id) ON DELETE CASCADE
-- );


-- INSERT INTO emp_int (id_emp, id_int) VALUES (38,3);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (38,6);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (38,9);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (39,3);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (39,6);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (39,8);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (39,9);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (40,1);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (40,6);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (40,8);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (40,9);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (41,2);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (41,3);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (41,5);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (41,6);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (41,9);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (42,1);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (42,6);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (42,8);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (42,9);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (43,1);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (43,6);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (43,8);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (43,9);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (44,2);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (44,5);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (44,6);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (44,7);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (44,9);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (45,6);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (45,9);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (46,6);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (46,9);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (47,6);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (47,9);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (48,6);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (48,9);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (49,3);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (49,6);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (49,8);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (49,9);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (50,2);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (50,3);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (50,5);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (50,6);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (50,9);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (51,2);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (51,3);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (51,5);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (51,6);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (51,8);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (51,9);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (52,2);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (52,5);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (52,6);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (52,7);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (52,9);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (53,2);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (53,5);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (53,6);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (53,7);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (53,9);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (54,2);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (54,5);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (54,6);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (54,7);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (54,9);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (55,2);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (55,5);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (55,6);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (55,7);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (55,9);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (56,2);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (56,5);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (56,6);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (56,7);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (56,9);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (57,3);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (57,4);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (57,6);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (57,8);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (57,9);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (58,3);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (58,4);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (58,6);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (58,8);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (58,9);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (59,3);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (59,4);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (59,6);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (59,8);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (59,9);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (60,3);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (60,4);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (60,6);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (60,8);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (60,9);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (61,3);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (61,4);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (61,6);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (61,8);
-- INSERT INTO emp_int (id_emp, id_int) VALUES (61,9);
-- 
-- 
-- CREATE TABLE filtro(
-- id serial PRIMARY KEY,
-- n_filtro int,
-- nome varchar(50),
-- valor int
-- );
-- 
-- INSERT INTO filtro (n_filtro, nome, valor) VALUES (1,'companhia/amigos',1);
-- INSERT INTO filtro (n_filtro, nome, valor) VALUES (1,'companhia/aDois',2);
-- INSERT INTO filtro (n_filtro, nome, valor) VALUES (1,'companhia/sozinho',3);
-- INSERT INTO filtro (n_filtro, nome, valor) VALUES (2,'financeiro/qualquer',1);
-- INSERT INTO filtro (n_filtro, nome, valor) VALUES (2,'financeiro/barato',2);
-- INSERT INTO filtro (n_filtro, nome, valor) VALUES (2,'financeiro/caro',3);

-- 
-- CREATE TABLE fil_emp(
-- id serial PRIMARY KEY,
-- id_fil int REFERENCES filtro(id) ON DELETE CASCADE,
-- id_emp int REFERENCES empresa(id) ON DELETE CASCADE
-- );
-- 
-- 
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (1,39);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (1,40);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (1,41);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (1,42);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (1,43);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (1,44);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (1,49);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (1,50);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (1,51);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (1,52);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (1,53);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (1,54);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (1,55);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (1,56);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (1,57);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (1,58);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (1,59);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (1,60);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (1,61);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (2,38);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (2,39);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (2,40);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (2,41);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (2,42);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (2,43);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (2,44);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (2,45);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (2,46);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (2,47);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (2,48);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (2,49);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (2,50);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (2,51);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (2,52);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (2,53);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (2,54);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (2,55);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (2,56);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (2,57);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (2,58);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (2,59);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (2,60);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (2,61);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (3,38);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (3,44);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (3,49);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (3,52);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (3,53);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (3,54);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (3,55);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (3,56);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (3,59);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (4,38);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (4,39);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (4,40);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (4,41);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (4,42);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (4,43);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (4,44);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (4,45);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (4,46);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (4,47);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (4,48);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (4,49);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (4,50);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (4,51);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (4,52);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (4,53);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (4,54);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (4,55);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (4,56);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (4,57);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (4,58);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (4,59);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (4,60);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (4,61);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (5,38);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (5,42);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (5,43);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (5,45);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (5,47);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (5,48);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (5,49);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (5,52);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (5,53);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (5,56);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (5,57);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (5,58);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (5,59);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (5,60);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (5,61);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (6,39);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (6,40);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (6,41);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (6,44);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (6,46);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (6,50);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (6,51);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (6,54);
-- INSERT INTO fil_emp (id_fil, id_emp) VALUES (6,55);


-- DROP TABLE usuario, empresa, interesse, us_int, emp_int;
-- SELECT * FROM empresa inner join fil_emp on empresa.id = fil_emp.id_emp inner join filtro on filtro.id = fil_emp.id_fil;
-- SELECT * FROM fil_emp inner join empresa on empresa.id = fil_emp.id_emp where id_fil = 1 OR id_fil = 2;
-- SELECT * FROM fil_emp inner join filtro on filtro.id = fil_emp.id_fil inner join empresa on empresa.id = fil_emp.id_emp;
-- SELECT DISTINCT empresa.nome, empresa.tipo FROM empresa INNER JOIN emp_int ON empresa.id = emp_int.id_emp INNER JOIN interesse ON interesse.id = emp_int.id_int inner join fil_emp on empresa.id = fil_emp.id_emp inner join filtro on filtro.id = fil_emp.id_fil WHERE interesse.id = 3;
-- SELECT * FROM empresa where carac like '' ;
-- DELETE FROM usuario where id=3;

ALTER TABLE empresa ADD COLUMN image_path VARCHAR(255) NOT NULL DEFAULT '';

